language: ruby
rvm:
  - "2.0.0"

branches:
  only:
    - wip
    - master

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3

script:
  - bundle exec rake jasmine:ci
