#Headless browser option
browser:
  phantomjs: "phantomjs"
  # slimerjs: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory: 'test_shots'
history_dir: 'baseline_shots'

# Add only 2 domains, key will act as a label
domains:
  local: "http://localhost:4567"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 768
  - 1024
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  revenda_prepanel: /documentacao/exemplos/painel1/pre-painel
  revenda_home: /documentacao/exemplos/painel1/home
  revenda_clients: /documentacao/exemplos/painel1/clients
  revenda_client: /documentacao/exemplos/painel1/client
  smtp_prepanel: /documentacao/exemplos/painel2/pre-painel
  smtp_home: /documentacao/exemplos/painel2/home
  smtp_report: /documentacao/exemplos/painel2/stats
  smtp_config: /documentacao/exemplos/painel2/config-server
  smtp_config_email: /documentacao/exemplos/painel2/config-email
  login: /documentacao/exemplos/login-screen
  error_404: /documentacao/exemplos/erro-404
#  all_elements: /documentacao/cartilha-de-elementos/
  boilerplate: /documentacao/exemplos/boilerplate

#Amount of fuzz ImageMagick will use
fuzz: '15%'

#Set the number of days to keep the site spider file
spider_days:
  - 10

#Choose how results are displayed, by default alphanumeric. Different screen widths are always grouped.
#alphanumeric - all paths (with, and without, a difference) are shown, sorted by path
#diffs_first - all paths (with, and without, a difference) are shown, sorted by difference size (largest first)
#diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
mode: diffs_first

threshold: 0.5
